### ISSUE TITLE
Hardcoded tolerance in Gauss-Legendre

### ISSUE THREAD

**Issue by susilehtola** [wavefunction91/IntegratorXX#40]
The Gauss-Legendre quadrature routine hardcodes an absolute tolerance `eps = 3.0e-11`. The origin of this value is not documented, and it also seems a bit too large to me. Since $x\in[-1,1]$, `eps` should be of the order of machine epsilon **of the employed data type**.

Another thing that needs to be fixed is to employ a `for` loop instead of the current `while` loop which risks hanging. Instead, one should take e.g. a maximum of 100 Newton iterations, and then throw an error if convergence was not achieved.

**Comment by wavefunction91** [comment]
Agreed
