### ISSUE TITLE
Do not use Approx in tests

### ISSUE THREAD

**Issue by susilehtola** [wavefunction91/IntegratorXX#44]
According to [the Catch2 documentation](https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md)
> We strongly recommend against using Approx when writing new code. You should be using floating point matchers instead.

The tests should accordingly use
- `WithinAbs(double target, double margin)`,
-  `WithinRel(FloatingPoint target, FloatingPoint eps)` and
- `WithinULP(FloatingPoint target, uint64_t maxUlpDiff)`

**Comment by wavefunction91** [comment]
To avoid a ton of merge conflicts, this should be held off until after #27 is merged

**Comment by wavefunction91** [comment]
Closed by #65
