### ISSUE TITLE
Extend tests to higher numbers of nodes and other rules

### ISSUE THREAD

**Issue by susilehtola** [wavefunction91/IntegratorXX#49]
#46 includes tests for low orders of nodes.

I think it would be good to also include tests for higher numbers of nodes, since quadrature grids often use even several hundreds of points.

However, not every number of points needs to be tested. I think that going from 100, it might be reasonable to test rules every 20 points, (100, 120, 140, 160, 180, 200), then maybe every 25 points (225, 250, 275, 300, 325, 350, 375, 400), then every 50 points (450, 500, 550, 600).

Reducing the spacing of the tests is a big reduction storage space, and the cost to generate the tests; even the 100-point rules take some seconds to generate on my laptop with SymPy...

The Gauss-Chebyshev rules 1 and 2 are found in SciPy; one just has to modify the weights, which can be done in the generator.

**Comment by susilehtola** [comment]
However, the Chevyshev rules are analytic, so the tests don't need to be as extensive compared to those of Legendre and Lobatto that actually involve root finding...

**Comment by wavefunction91** [comment]
Just to note that having this in place will be useful if we move faster algorithms for e.g. Gauss-Legendre ala

[SIAM J. Sci. Comput., 36 (2014), C1008–C1026.](https://doi.org/10.1137/140954969)

https://github.com/cenit/jburkardt/tree/master/fastgl

**Comment by wavefunction91** [comment]
@susilehtola I have a workstation working on this now, but if you're already working on it, I can cancel the jobs. Let me know.

**Comment by wavefunction91** [comment]
This will be closed by #52
